name: Test
on: pull_request

jobs:
  node-linters:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@master
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: npm i
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
